export type ProjectCategory = 'Sand Mining' | 'Limestone Mining' | 'Brick Kiln' | 'Infrastructure Projects' | 'Industrial Projects';

export const PROJECT_CATEGORIES: ProjectCategory[] = [
  'Sand Mining',
  'Limestone Mining',
  'Brick Kiln',
  'Infrastructure Projects',
  'Industrial Projects'
];

export const WORKFLOW_STAGES = [
  'Draft',
  'Submitted',
  'Under review',
  'Deficiency raised',
  'Applicant response',
  'Committee review',
  'Approved',
  'Rejected'
] as const;


export type WorkflowStage = typeof WORKFLOW_STAGES[number];

export interface ChecklistItem {
  id: string;
  name: string;
  category: 'Administrative' | 'Technical'| 'Legal' | 'Environmental' | 'Clearances' | 'GIS';
}

export const CATEGORY_CHECKLISTS: Record<ProjectCategory, ChecklistItem[]> = {
  'Sand Mining': [
    { id: 'sm-1', name: 'Processing fee details', category: 'Administrative' },
    { id: 'sm-2', name: 'Pre feasibility report', category: 'Technical' },
    { id: 'sm-3', name: 'EMP', category: 'Environmental' },
    { id: 'sm-4', name: 'Form 1 or CAF', category: 'Administrative' },
    { id: 'sm-5', name: 'District survey report or sand replenishment study', category: 'Technical' },
    { id: 'sm-6', name: 'Land documents', category: 'Legal' },
    { id: 'sm-7', name: 'LOI', category: 'Legal' },
    { id: 'sm-8', name: 'Gram Panchayat NOC', category: 'Clearances' },
    { id: 'sm-9', name: '200 meter certificate', category: 'Clearances' },
    { id: 'sm-10', name: '500 meter certificate', category: 'Clearances' },
    { id: 'sm-11', name: 'Marked and delimited copy', category: 'Legal' },
    { id: 'sm-12', name: 'Mining plan approval letter', category: 'Clearances' },
    { id: 'sm-13', name: 'Approved mining plan', category: 'Technical' },
    { id: 'sm-14', name: 'Forest NOC', category: 'Clearances' },
    { id: 'sm-15', name: 'KML file', category: 'GIS' },
    { id: 'sm-16', name: 'CER details', category: 'Environmental' },
    { id: 'sm-17', name: 'Affidavits', category: 'Legal' },
    { id: 'sm-18', name: 'GIST submission', category: 'Technical' },
  ],
  'Limestone Mining': [
    { id: 'lm-1', name: 'Processing fee details', category: 'Administrative' },
    { id: 'lm-2', name: 'Pre feasibility report', category: 'Technical' },
    { id: 'lm-3', name: 'EMP', category: 'Environmental' },
    { id: 'lm-4', name: 'Form 1 or CAF', category: 'Administrative' },
    { id: 'lm-5', name: 'District survey report', category: 'Technical' },
    { id: 'lm-6', name: 'Land documents', category: 'Legal' },
    { id: 'lm-7', name: 'Landowner consent', category: 'Legal' },
    { id: 'lm-8', name: 'LOI', category: 'Legal' },
    { id: 'lm-9', name: 'Lease deed', category: 'Legal' },
    { id: 'lm-10', name: 'Previous environmental clearance', category: 'Clearances' },
    { id: 'lm-11', name: 'Compliance report', category: 'Environmental' },
    { id: 'lm-12', name: 'Past production certificate', category: 'Technical' },
    { id: 'lm-13', name: 'Gram Panchayat NOC', category: 'Clearances' },
    { id: 'lm-14', name: '200 meter certificate', category: 'Clearances' },
    { id: 'lm-15', name: '500 meter certificate', category: 'Clearances' },
    { id: 'lm-16', name: 'Mining plan approval letter', category: 'Clearances' },
    { id: 'lm-17', name: 'Approved mining plan', category: 'Technical' },
    { id: 'lm-18', name: 'Forest NOC', category: 'Clearances' },
    { id: 'lm-19', name: 'Tree plantation compliance', category: 'Environmental' },
    { id: 'lm-20', name: 'Water NOC', category: 'Clearances' },
    { id: 'lm-21', name: 'CTE or CTO', category: 'Clearances' },
    { id: 'lm-22', name: 'Geo tagged photographs', category: 'GIS' },
    { id: 'lm-23', name: 'Boundary strip restoration plan', category: 'Environmental' },
    { id: 'lm-24', name: 'Drone video', category: 'GIS' },
    { id: 'lm-25', name: 'KML file', category: 'GIS' },
    { id: 'lm-26', name: 'Certified compliance report', category: 'Environmental' },
    { id: 'lm-27', name: 'CEMP', category: 'Environmental' },
    { id: 'lm-28', name: 'CER details', category: 'Environmental' },
    { id: 'lm-29', name: 'Affidavits', category: 'Legal' },
    { id: 'lm-30', name: 'EIA report', category: 'Technical' },
    { id: 'lm-31', name: 'GIST submission', category: 'Technical' },
  ],
  'Brick Kiln': [
    { id: 'bk-1', name: 'Processing fee details', category: 'Administrative' },
    { id: 'bk-2', name: 'Pre feasibility report', category: 'Technical' },
    { id: 'bk-3', name: 'EMP', category: 'Environmental' },
    { id: 'bk-4', name: 'Form 1 or CAF', category: 'Administrative' },
    { id: 'bk-5', name: 'District survey report', category: 'Technical' },
    { id: 'bk-6', name: 'Land documents', category: 'Legal' },
    { id: 'bk-7', name: 'Landowner consent', category: 'Legal' },
    { id: 'bk-8', name: 'LOI', category: 'Legal' },
    { id: 'bk-9', name: 'Lease deed', category: 'Legal' },
    { id: 'bk-10', name: 'Previous environmental clearance', category: 'Clearances' },
    { id: 'bk-11', name: 'Compliance report', category: 'Environmental' },
    { id: 'bk-12', name: 'Production certificate', category: 'Technical' },
    { id: 'bk-13', name: 'Gram Panchayat NOC', category: 'Clearances' },
    { id: 'bk-14', name: 'Panchnama', category: 'Legal' },
    { id: 'bk-15', name: '200 meter certificate', category: 'Clearances' },
    { id: 'bk-16', name: '500 meter certificate', category: 'Clearances' },
    { id: 'bk-17', name: 'Mining plan approval letter', category: 'Clearances' },
    { id: 'bk-18', name: 'Approved mining plan', category: 'Technical' },
    { id: 'bk-19', name: 'Forest NOC', category: 'Clearances' },
    { id: 'bk-20', name: 'Tree plantation compliance', category: 'Environmental' },
    { id: 'bk-21', name: 'Water NOC', category: 'Clearances' },
    { id: 'bk-22', name: 'CTE or CTO', category: 'Clearances' },
    { id: 'bk-23', name: 'Geo tagged photographs', category: 'GIS' },
    { id: 'bk-24', name: 'Boundary strip restoration plan', category: 'Environmental' },
    { id: 'bk-25', name: 'Drone video', category: 'GIS' },
    { id: 'bk-26', name: 'KML file', category: 'GIS' },
    { id: 'bk-27', name: 'Certified compliance report', category: 'Environmental' },
    { id: 'bk-28', name: 'CEMP', category: 'Environmental' },
    { id: 'bk-29', name: 'CER details', category: 'Environmental' },
    { id: 'bk-30', name: 'Affidavits', category: 'Legal' },
    { id: 'bk-31', name: 'EIA report', category: 'Technical' },
    { id: 'bk-32', name: 'GIST submission', category: 'Technical' },
  ],
  'Infrastructure Projects': [
    { id: 'in-1', name: 'Processing fee details', category: 'Administrative' },
    { id: 'in-2', name: 'Pre feasibility report', category: 'Technical' },
    { id: 'in-3', name: 'EMP', category: 'Environmental' },
    { id: 'in-4', name: 'Form 1 or CAF', category: 'Administrative' },
    { id: 'in-5', name: 'Land documents', category: 'Legal' },
    { id: 'in-6', name: 'Previous environmental clearance', category: 'Clearances' },
    { id: 'in-7', name: 'Compliance report', category: 'Environmental' },
    { id: 'in-8', name: 'Ownership consent', category: 'Legal' },
    { id: 'in-9', name: 'Conceptual plan', category: 'Technical' },
    { id: 'in-10', name: 'Approved layout', category: 'Technical' },
    { id: 'in-11', name: 'Land use zoning map', category: 'GIS' },
    { id: 'in-12', name: 'Built up area statement', category: 'Technical' },
    { id: 'in-13', name: 'Building permission', category: 'Clearances' },
    { id: 'in-14', name: 'Water permission', category: 'Clearances' },
    { id: 'in-15', name: 'STP design and reuse plan', category: 'Technical' },
    { id: 'in-16', name: 'Solid waste management plan', category: 'Technical' },
    { id: 'in-17', name: 'Solar energy plan', category: 'Technical' },
    { id: 'in-18', name: 'Green belt area statement', category: 'Environmental' },
    { id: 'in-19', name: 'EMP cost estimates', category: 'Environmental' },
    { id: 'in-20', name: 'NBWL clearance', category: 'Clearances' },
    { id: 'in-21', name: 'Fire NOC', category: 'Clearances' },
    { id: 'in-22', name: 'Aviation NOC', category: 'Clearances' },
    { id: 'in-23', name: 'Wildlife management plan', category: 'Environmental' },
    { id: 'in-24', name: 'CTE or CTO', category: 'Clearances' },
    { id: 'in-25', name: 'Geo tagged photographs', category: 'GIS' },
    { id: 'in-26', name: 'KML file', category: 'GIS' },
    { id: 'in-27', name: 'CER details', category: 'Environmental' },
    { id: 'in-28', name: 'Affidavits', category: 'Legal' },
    { id: 'in-29', name: 'EIA report', category: 'Technical' },
    { id: 'in-30', name: 'GIST submission', category: 'Technical' },
  ],
  'Industrial Projects': [
    { id: 'id-1', name: 'Processing fee details', category: 'Administrative' },
    { id: 'id-2', name: 'Pre feasibility report', category: 'Technical' },
    { id: 'id-3', name: 'EMP', category: 'Environmental' },
    { id: 'id-4', name: 'Form 1 or CAF', category: 'Administrative' },
    { id: 'id-5', name: 'Land documents', category: 'Legal' },
    { id: 'id-6', name: 'Landowner consent', category: 'Legal' },
    { id: 'id-7', name: 'Lease deed', category: 'Legal' },
    { id: 'id-8', name: 'Previous environmental clearance', category: 'Clearances' },
    { id: 'id-9', name: 'Compliance report', category: 'Environmental' },
    { id: 'id-10', name: 'Production certificate', category: 'Technical' },
    { id: 'id-11', name: 'Gram Panchayat NOC', category: 'Clearances' },
    { id: 'id-12', name: 'Forest NOC', category: 'Clearances' },
    { id: 'id-13', name: 'Tree plantation compliance', category: 'Environmental' },
    { id: 'id-14', name: 'Land use breakup', category: 'Technical' },
    { id: 'id-15', name: 'ETP details', category: 'Technical' },
    { id: 'id-16', name: 'Fire NOC', category: 'Clearances' },
    { id: 'id-17', name: 'Water permission', category: 'Clearances' },
    { id: 'id-18', name: 'Water NOC', category: 'Clearances' },
    { id: 'id-19', name: 'STP design', category: 'Technical' },
    { id: 'id-20', name: 'EMP cost estimates', category: 'Environmental' },
    { id: 'id-21', name: 'CTE or CTO', category: 'Clearances' },
    { id: 'id-22', name: 'ToR granted', category: 'Clearances' },
    { id: 'id-23', name: 'EIA report', category: 'Technical' },
    { id: 'id-24', name: 'Wildlife management plan', category: 'Environmental' },
    { id: 'id-25', name: 'Affidavit on pending litigation', category: 'Legal' },
    { id: 'id-26', name: 'Compliance affidavits', category: 'Legal' },
    { id: 'id-27', name: 'Drone video', category: 'GIS' },
    { id: 'id-28', name: 'Certified compliance report', category: 'Environmental' },
    { id: 'id-29', name: 'CEMP', category: 'Environmental' },
    { id: 'id-30', name: 'CER details', category: 'Environmental' },
    { id: 'id-31', name: 'GIST submission', category: 'Technical' },
  ],
};

export const DEFICIENCY_ITEMS = [
  "Processing fee details missing",
  "Pre feasibility report missing",
  "Certified Air and Water compliance report missing",
  "LOI missing or expired",
  "Mining plan approval missing",
  "Approved mining plan missing",
  "Forest clearance missing",
  "Land documents missing",
  "Land owner consent missing",
  "200 meter certificate missing",
  "500 meter certificate missing",
  "Gram Panchayat NOC missing",
  "District Survey Report missing",
  "Sand replenishment study missing",
  "Marked and delimited copy missing",
  "Forest NOC revision required",
  "CEMP details missing",
  "Updated EIA report missing",
  "Wildlife conservation plan missing",
  "Water NOC missing",
  "Production certificate missing",
  "Plantation compliance report missing",
  "Geo tagged photographs missing",
  "Restoration plan missing",
  "Panchnama missing",
  "Environmental clearance copy missing",
  "Layout approval missing",
  "Land use zoning map missing",
  "Building permission missing",
  "STP design missing",
  "Solid waste management plan missing",
  "Solar energy plan missing",
  "Green belt plan missing",
  "EMP cost estimate missing",
  "NBWL clearance missing",
  "Fire NOC missing",
  "Aviation NOC missing",
  "Lease deed missing",
  "KML file missing",
  "Drone video missing",
  "CER details missing",
  "Affidavits missing"
];
