import { useState, useEffect } from 'react';
import { API_BASE_URL } from '../../config';
import { useAuth } from '../../context/AuthContext';
import { Shield, Download, FileText } from 'lucide-react';
import DataTable, { ColumnDef } from '../ui/DataTable';
import StatusBadge from '../ui/StatusBadge';
import SearchFilterBar, { FilterConfig } from '../ui/SearchFilterBar';
import PaginationControls from '../ui/PaginationControls';

export default function ComplianceReports() {
  const [projects, setProjects] = useState<any[]>([]);
  const [search, setSearch] = useState('');
  const [statusFilter, setStatusFilter] = useState('');
  const [currentPage, setCurrentPage] = useState(1);
  const itemsPerPage = 8;
  const { token, user } = useAuth();
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch(`${API_BASE_URL}/api/projects`, { headers: { Authorization: `Bearer ${token}` } })
      .then(r => r.json())
      .then(data => {
        const mine = data.filter((p: any) =>
          p.applicant === user?.organization || p.applicant === user?.name
        );
        // Add random mock IDs/data for demo if missing
        const augmented = mine.map((p: any, i: number) => ({
           ...p,
           id: p.id || i + 2000,
           type: p.type || 'Infrastructure',
           reportDate: new Date(Date.now() - Math.random() * 10000000000).toISOString(),
           score: p.riskScore || Math.floor(Math.random() * 100),
           reportId: `CR-2026-${Math.floor(Math.random() * 9000) + 1000}`,
        }));
        setProjects(augmented);
      })
      .finally(() => setLoading(false));
  }, [token, user]);

  const filtered = projects.filter(p => {
    const sMatch = p.title.toLowerCase().includes(search.toLowerCase()) || p.reportId.toLowerCase().includes(search.toLowerCase());
    const fMatch = !statusFilter || statusFilter === 'All' || p.status === statusFilter;
    return sMatch && fMatch;
  });

  const paginated = filtered.slice((currentPage - 1) * itemsPerPage, currentPage * itemsPerPage);

  const filterConfigs: FilterConfig[] = [
    {
      label: 'Clearance Status',
      value: statusFilter,
      onChange: setStatusFilter,
      options: [
         { value: 'All', label: 'All Statuses' },
         { value: 'Pending', label: 'Pending Submission' },
         { value: 'Under Review', label: 'Under Review' },
         { value: 'Approved', label: 'Approved' },
         { value: 'Rejected', label: 'Rejected' },
      ],
      icon: <Shield size={16} />
    }
  ];

  const handleDownload = (p: any) => {
    const report = [
      `OFFICIAL COMPLIANCE & RISK REPORT - MOEFCC`,
      `=============================================`,
      `Report ID: ${p.reportId}`,
      `Project: ${p.title}`,
      `Applicant: ${p.applicant}`,
      `Status: ${p.status}`,
      `AI Assessed Risk Score: ${p.score}/100`,
      `Generation Date: ${new Date(p.reportDate).toLocaleDateString()}`,
      ``,
      `Summary:`,
      p.riskSummary || 'Standard compliance checks completed. AI monitoring active.',
      ``,
      `Generated by Parivesh 3.0/PARIVESH AI on ${new Date().toLocaleString()}`,
    ].join('\n');
    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${p.reportId}_compliance.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const columns: ColumnDef<any>[] = [
    { header: 'Report ID', accessorKey: 'reportId',
      cell: (p) => <span className="text-zinc-300 font-mono text-xs">{p.reportId}</span>
    },
    { header: 'Project / Facility', accessorKey: 'title', 
      cell: (p) => (
         <div>
           <p className="font-semibold text-zinc-100 text-sm">{p.title}</p>
           <p className="text-[10px] text-zinc-500 mt-0.5">{p.type}</p>
         </div>
      )
    },
    { header: 'Report Date', accessorKey: 'reportDate',
      cell: (p) => <span className="text-zinc-400 text-sm whitespace-nowrap">{new Date(p.reportDate).toLocaleDateString()}</span>
    },
    { header: 'Project Status', accessorKey: 'status',
      cell: (p) => <StatusBadge status={p.status} size="sm" />
    },
    { header: 'AI Risk Score', accessorKey: 'score',
      cell: (p) => (
         <div className="flex items-center gap-2 w-28">
           <div className="flex-1 h-1.5 bg-zinc-800 rounded-full overflow-hidden">
             <div className={`h-full ${p.score > 70 ? 'bg-red-500' : p.score > 30 ? 'bg-amber-500' : 'bg-emerald-500'}`} style={{ width: `${p.score}%` }} />
           </div>
           <span className={`text-xs font-bold ${p.score > 70 ? 'text-red-400' : p.score > 30 ? 'text-amber-400' : 'text-emerald-400'}`}>{p.score}/100</span>
         </div>
      )
    },
    { header: '', accessorKey: 'id',
      cell: (p) => (
         <button onClick={(e) => { e.stopPropagation(); handleDownload(p); }} className="flex items-center gap-2 px-3 py-1.5 bg-zinc-800 hover:bg-zinc-700 text-zinc-300 text-xs font-semibold rounded-lg transition-colors ml-auto">
           <Download size={14} /> PDF
         </button>
      )
    }
  ];

  return (
    <div className="p-6 md:p-10 max-w-6xl mx-auto space-y-6 fade-up">
      <header>
        <p className="text-xs text-zinc-500 uppercase font-semibold tracking-widest mb-1">Applicant · Reports</p>
        <h1 className="text-3xl font-black text-white">Compliance Reports</h1>
        <p className="text-zinc-400 text-sm mt-1">Download official AI-generated environmental risk assessments and monitoring reports.</p>
      </header>

      <div className="bg-[#0f1f4a]/80 border border-zinc-800 rounded-2xl overflow-hidden shadow-2xl">
        <div className="p-5 border-b border-zinc-800/80">
          <SearchFilterBar 
            searchQuery={search}
            onSearchChange={setSearch}
            placeholder="Search by report ID or project title..."
            filters={filterConfigs}
          />
        </div>

        <DataTable
          columns={columns}
          data={paginated}
          isLoading={loading}
          emptyStateTitle="No compliance reports found"
          emptyStateMessage="No generated reports match your current filters."
          emptyStateIcon={FileText}
          onRowClick={handleDownload}
        />

        {filtered.length > 0 && (
           <div className="p-4 bg-zinc-950/50 border-t border-zinc-800/50">
             <PaginationControls
                currentPage={currentPage}
                totalItems={filtered.length}
                itemsPerPage={itemsPerPage}
                onPageChange={setCurrentPage}
             />
           </div>
        )}
      </div>
    </div>
  );
}
